export const territorios = [
    {
        id: 1,
        nome: "Territorio 1",
        imagem: "https://cdn.discordapp.com/attachments/944325890819641436/1181565807776497764/image.png?ex=658185e9&is=656f10e9&hm=e3af50bef67b73bb584640349d1ce9fcb4f3a5d00551d85c7f48f85909a39fcc&",
    },
    {
        id: 2,
        nome: "Territorio 2",
        imagem: "https://cdn.discordapp.com/attachments/944325890819641436/1181566165043134535/image.png?ex=6581863e&is=656f113e&hm=980e683c64a0d3fdf6ed943fca0b89feb05547a27cde632ac5440a922faafc22&",
    },
    {
        id: 3,
        nome: "Territorio 3",
        imagem: "https://cdn.discordapp.com/attachments/944325890819641436/1181566777252118538/image.png?ex=658186d0&is=656f11d0&hm=8fae1424e727acb8653a2fcefbf3ae5c28bcd0506b54d4b4cad0d140bc430b0f&",
    },
    {
        id: 4,
        nome: "Territorio 4",
        imagem: "https://cdn.discordapp.com/attachments/944325890819641436/1181567862347935875/image.png?ex=658187d2&is=656f12d2&hm=5ce7c76a865984d937d8b6b3ea390e3d67f0942a23040ba909fef1abb26a7dcb&",
    },
    {
        id: 5,
        nome: "Territorio 5",
        imagem: "https://cdn.discordapp.com/attachments/944325890819641436/1181567032743952454/image.png?ex=6581870d&is=656f120d&hm=90fb9337c4e22829614b1ff5189295807a8ea87adc67f33191a940d9f535a21d&",
    },
    {
        id: 6,
        nome: "Territorio 6",
        imagem: "https://cdn.discordapp.com/attachments/944325890819641436/1181567217314316328/image.png?ex=65818739&is=656f1239&hm=7420ae244c48db8053abfffb1626074a43ff1039a82c9ee340a8a7e282fff045&",
    },
];

export const animais = [
    {
        id: 1,
        animal: [
            ["Elefante",
            "O elefante-da-savana também conhecido como elefante-africano é a maior das duas espécies existentes de elefantes africano e o maior animal terrestre vivo. ",
            "https://static.biologianet.com/2020/05/elefante-africano.jpg",
            "Loxodonta africana",
            ],
            ["Arara",
            "A arara-macau é uma espécie de ave pertencente à família Psittacidae, sendo a terceira maior representante do gênero Ara. Ocupa um grande território na América que vai do sul do México até o norte do estado brasileiro do Mato Grosso.",
            "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/44409341/1800",
            "Ara macao",
            ],
            ["Raposinha-do-campo",
            "A raposinha-do-campo é um canídeo endêmico do Brasil, que habita os campos e cerrados em uma área de distribuição que inclui o Mato Grosso, Mato Grosso do Sul, Goiás, Minas Gerais e São Paulo.",
            "https://upload.wikimedia.org/wikipedia/commons/5/5a/Lycalopex_vetulus_Carlos_Henrique_2.jpeg",
            "Lycalopex vetulus",
            ],
            ["Rinoceronte",
            "O rinoceronte é um mamífero encontrado no Nepal e na Índia, estando actualmente confinado a pradarias altas e florestas no sopé dos Himalaias.",
            "https://www.aspinallfoundation.org/media/6610/dsc_0753_small.jpg?center=0.32972972972972975,0.358695652173913&mode=crop&quality=75&width=934&height=495&rnd=133023694460000000",
            "Rhinoceros unicornis",
            ],
            ["Águia",
            "A águia-real é uma ave de rapina europeia, de hábitos diurnos, da família Accipitridae. Habita em grande parte do Hemisfério Norte: Europa, Ásia, Norte da África e grande parte da América do Norte.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Беркут_%28Aquila_chrysaetos%29.jpg/1280px-Беркут_%28Aquila_chrysaetos%29.jpg",
            "Aquila chrysaetos",
            ],
            ["Chimpanzé",
            "O chimpanzé-comum é uma das duas espécies de chimpanzés que vivem no continente africano, juntamente com o chimpanzé-pigmeu. São os parentes vivos mais próximos dos humanos.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pan_troglodytes_%28male%29.jpg/1280px-Pan_troglodytes_%28male%29.jpg",
            "Pan troglodytes",
            ],
        ],
    },
    {
        id: 2,
        animal: [
            ["Jacaré",
            "O jacaré-açu é uma espécie de jacaré exclusiva da América do Sul. Também conhecido como jacaré-negro ou jacaré-preto, é um predador de topo de cadeia alimentar.",
            "https://cdn.ambientes.ambientebrasil.com.br/wp-content/uploads/2020/11/jacare-2645898_1280-1024x682.jpg",
            "Melanosuchus niger",
            ],
            ["Papagaio",
            "O papagaio-verdadeiro, é uma ave da família dos psitacídeos, nativa do Brasil oriental. É uma das espécies mais inteligentes de ave no planeta, e costumam imitar os sons dos seus donos.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Papagaio-verdadeiro.jpg/1280px-Papagaio-verdadeiro.jpg",
            "Amazona aestiva",
            ],
            ["Cachorro-do-mato",
            "O cachorro do mato é uma espécie de canídeo endêmico da América do Sul. Habita as regiões costeiras e montanhosas, adaptando-se a altitudes até 3 000 metros. Três subespécies podem ser encontradas no Brasil.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Crab-eating_Fox_%28cropped%29.JPG/420px-Crab-eating_Fox_%28cropped%29.JPG",
            "Cerdocyon thous",
            ],
            ["Zebra",
            "A zebra vive em regiões montanhosas limitadas às províncias ocidentais da África do Sul e Cabo Ocidental. Esta espécie se alimenta de grama mas em tempos de escassez se alimenta de arbustos e pequenas árvores.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Equus_zebra_-_Disney%27s_Animal_Kingdom_Lodge%2C_Orlando%2C_Florida%2C_USA_-_20100119.jpg/1024px-Equus_zebra_-_Disney%27s_Animal_Kingdom_Lodge%2C_Orlando%2C_Florida%2C_USA_-_20100119.jpg",
            "Equus zebra",
            ],
            ["Harpia",
            "A harpia é a maior e mais poderosa ave de rapina encontrada em toda a sua extensão e está entre as maiores espécies de águias existentes no mundo.",
            "https://s3.amazonaws.com/media.wikiaves.com.br/images/5073/3705980_2ac35d5396d5c4efdd60bc87979fc490.jpg",
            "Harpia Harpyja",
            ],
            ["Orangotango",
            "O orangotango é o terceiro primata vivo mais pesado, logo a seguir às duas espécies de gorila e são os maiores animais arborícolas do mundo. O orangotango têm os braços muito longos, que podem atingir até 2 m de comprimento.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Orangutan-Columbus-zoo.JPG/1200px-Orangutan-Columbus-zoo.JPG",
            "Pongo pygmaeus",
            ],
            ],
    },
    {
        id: 3,
        animal: [
            ["Flamingo",
            "Os flamingos são aves pernaltas, de bico encurvado, que medem entre 90 e 150 cm. Sua coloração vem da alimentação rica em carotenos, que são pigmentos que eles conseguem através de algas e camarões.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Caribbean_Flamingo.jpg/1200px-Caribbean_Flamingo.jpg",
            "Phoenicopterus roseus",
            ],
            ["Serpente",
            "As cascavéis possuem um chocalho característico na cauda, e estão presentes em todo o continente americano. A cascavel, em vez de sair completamente de sua pele antiga, mantém parte dela enrolada na cauda em forma de um anel.",
            "https://conteudo.imguol.com.br/c/entretenimento/d7/2021/11/22/cobra-cascavel-1637587568299_v2_1920x1308.jpg",
            "Ophiophagus hannah",
            ],
            ["Tamanduá-bandeira",
            "O tamanduá-bandeira é a maior das quatro espécies de tamanduás e, junto com as preguiças, está incluído na ordem Pilosa. O tamanduá se alimenta exclusivamente de formigas e cupins.",
            "https://upload.wikimedia.org/wikipedia/commons/3/3b/Myresluger2.jpg",
            "Myrmecophaga tridactyla",
            ],
            ["Girafa",
            "As girafas são mamíferos distintivos da savana africana, caracterizadas por seus longos pescoços e pernas esguias, tornando-as os animais mais altos do planeta, com mais de seis metros de altura.",
            "https://static.nationalgeographicbrasil.com/files/styles/image_3200/public/nationalgeographic2790911.jpg?w=710&h=474",
            "Giraffa giraffa",
            ],
            ["Urubu-rei",
            "O Urubu-rei habita todo o território brasileiro, tem a parte superior do corpo amarelo-clara, esbranquiçada, asas e cauda pretas, o lado inferior branco, com plumagem branca e negra.",
            "https://pbs.twimg.com/media/EnCeKx6XEAExA_c.jpg",
            "Sarcoramphus papa",
            ],
            ["Muriqui-do-sul",
            "Com quase 1,60 m de comprimento e pesando até 15 kg, o muriqui do sul é o maior primata não-humano das Américas. Ao contrário do muriqui-do-norte, sua face é negra, sem manchas esbranquiçadas, e não possui o polegar vestigial.",
            "https://i0.wp.com/oeco.org.br/wp-content/uploads/2022/01/20211016-1334-00823.jpg?resize=640%2C427&ssl=1",
            "Elephas maximus",
            "Brachyteles arachnoides",
            ],
        ],
    }
];
